add dockerfile
libp2p/go-libp2p-relay-daemon pull request #17
Opened 2022-06-13 12:43 UTC by coryschwartz

2022-06-13 12:58 UTC, marten-seemann requested changes
This doesn't build the current master, this builds the latest release.

2022-06-13 12:58 UTC, marten-seemann commented on Dockerfile
> +RUN go mod download
I don't think you need this, `go build` will download dependencies.

2022-06-15 06:00 UTC, coryschwartz commented on Dockerfile
> +RUN go mod download
True.

The reason I did this was to make the build a little faster. download on the first run, and then subsequent runs would be able to use this docker layer.

2022-06-20 07:55 UTC, coryschwartz commented on Dockerfile
> +RUN go mod download
Edited, so it doesn't run go mod download.

2022-06-30 22:52 UTC, coryschwartz commented
@marten-seemann Does this look okay now?

For context, I'm intending to use this on kubernetes with with IPFS nodes to do hole punching using this.

2022-07-01 11:07 UTC, hsanjuan commented
> This doesn't build the current master, this builds the latest release.

I don't understand this comment. I think it worked fine with `go mod download`? This is a common pattern ([i.e.](https://petomalina.medium.com/using-go-mod-download-to-speed-up-golang-docker-builds-707591336888))

2022-07-01 14:04 UTC, marten-seemann approved these changes

2022-07-20 15:59 UTC, merged